// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikY.Repository.Persistence.Contexts;

#nullable disable

namespace WikY.Repository.Migrations
{
    [DbContext(typeof(WikYDbContext))]
    partial class WikYDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WikY.Entities.Articles.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("WikY.Entities.Authors.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Author", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0853870-fbf9-4484-9d66-ac475ae8f332"),
                            CreatedAt = new DateTime(2022, 10, 2, 15, 20, 9, 190, DateTimeKind.Local).AddTicks(2301),
                            FirstName = "Ginger",
                            LastName = "Lueilwitz",
                            UpdatedAt = new DateTime(2023, 4, 5, 2, 17, 40, 326, DateTimeKind.Local).AddTicks(9486)
                        },
                        new
                        {
                            Id = new Guid("0ace333a-7668-49a3-a40d-f06a2243ebdf"),
                            CreatedAt = new DateTime(2023, 3, 22, 17, 17, 2, 846, DateTimeKind.Local).AddTicks(9581),
                            FirstName = "Jesse",
                            LastName = "Dicki",
                            UpdatedAt = new DateTime(2023, 2, 18, 8, 12, 55, 563, DateTimeKind.Local).AddTicks(6030)
                        },
                        new
                        {
                            Id = new Guid("fee776be-710c-470d-ae1a-c64600f57cbf"),
                            CreatedAt = new DateTime(2022, 12, 4, 14, 14, 41, 185, DateTimeKind.Local).AddTicks(2519),
                            FirstName = "Debra",
                            LastName = "Gerhold",
                            UpdatedAt = new DateTime(2023, 5, 11, 14, 9, 20, 673, DateTimeKind.Local).AddTicks(8834)
                        },
                        new
                        {
                            Id = new Guid("d2bc18b7-7be8-4f22-ba16-232a8d54946c"),
                            CreatedAt = new DateTime(2023, 6, 9, 18, 22, 23, 156, DateTimeKind.Local).AddTicks(35),
                            FirstName = "Franklin",
                            LastName = "Kessler",
                            UpdatedAt = new DateTime(2023, 4, 10, 17, 46, 18, 229, DateTimeKind.Local).AddTicks(2619)
                        },
                        new
                        {
                            Id = new Guid("304675fc-2584-4d33-8086-9d667fc0078f"),
                            CreatedAt = new DateTime(2023, 2, 16, 7, 0, 44, 753, DateTimeKind.Local).AddTicks(1016),
                            FirstName = "Jesus",
                            LastName = "Kilback",
                            UpdatedAt = new DateTime(2024, 1, 11, 4, 7, 39, 399, DateTimeKind.Local).AddTicks(954)
                        },
                        new
                        {
                            Id = new Guid("d9bd148a-fa61-4a94-8c64-9290e9980f1b"),
                            CreatedAt = new DateTime(2022, 7, 7, 0, 44, 50, 469, DateTimeKind.Local).AddTicks(1910),
                            FirstName = "Katrina",
                            LastName = "Medhurst",
                            UpdatedAt = new DateTime(2023, 10, 10, 4, 28, 54, 176, DateTimeKind.Local).AddTicks(8054)
                        },
                        new
                        {
                            Id = new Guid("7af34ad3-12fe-437a-b072-82f3500ca4c8"),
                            CreatedAt = new DateTime(2023, 2, 25, 22, 33, 14, 23, DateTimeKind.Local).AddTicks(1543),
                            FirstName = "Kathryn",
                            LastName = "Feest",
                            UpdatedAt = new DateTime(2023, 1, 29, 22, 41, 5, 321, DateTimeKind.Local).AddTicks(2020)
                        },
                        new
                        {
                            Id = new Guid("9edf7a1e-3973-4371-9641-d854ea42c895"),
                            CreatedAt = new DateTime(2023, 5, 23, 14, 23, 53, 393, DateTimeKind.Local).AddTicks(8104),
                            FirstName = "Olive",
                            LastName = "Rau",
                            UpdatedAt = new DateTime(2023, 1, 21, 5, 51, 9, 153, DateTimeKind.Local).AddTicks(7396)
                        },
                        new
                        {
                            Id = new Guid("5ab01bd3-8871-4cea-b6ae-6167a05d8ef6"),
                            CreatedAt = new DateTime(2023, 11, 19, 6, 36, 25, 436, DateTimeKind.Local).AddTicks(6959),
                            FirstName = "Arturo",
                            LastName = "Brakus",
                            UpdatedAt = new DateTime(2023, 1, 22, 5, 9, 56, 458, DateTimeKind.Local).AddTicks(5533)
                        },
                        new
                        {
                            Id = new Guid("86edd07f-7d4c-4858-b269-1a3ecb6b2a76"),
                            CreatedAt = new DateTime(2022, 12, 8, 16, 38, 8, 464, DateTimeKind.Local).AddTicks(9890),
                            FirstName = "Jean",
                            LastName = "Crist",
                            UpdatedAt = new DateTime(2023, 2, 16, 8, 36, 24, 33, DateTimeKind.Local).AddTicks(2258)
                        },
                        new
                        {
                            Id = new Guid("e3e1885e-f0bf-4c41-8ee9-c4851260ce54"),
                            CreatedAt = new DateTime(2023, 6, 26, 1, 29, 4, 109, DateTimeKind.Local).AddTicks(8534),
                            FirstName = "Miguel",
                            LastName = "Trantow",
                            UpdatedAt = new DateTime(2023, 6, 23, 19, 57, 25, 643, DateTimeKind.Local).AddTicks(8904)
                        },
                        new
                        {
                            Id = new Guid("81d6e537-66fd-4970-8b78-b3bacf6817cd"),
                            CreatedAt = new DateTime(2023, 1, 6, 11, 2, 49, 929, DateTimeKind.Local).AddTicks(2413),
                            FirstName = "Karl",
                            LastName = "Legros",
                            UpdatedAt = new DateTime(2023, 3, 7, 9, 53, 6, 968, DateTimeKind.Local).AddTicks(3409)
                        },
                        new
                        {
                            Id = new Guid("a1d0d0c0-07f6-420a-8fc0-b9e8c1ddf5b8"),
                            CreatedAt = new DateTime(2023, 6, 5, 19, 37, 42, 618, DateTimeKind.Local).AddTicks(2857),
                            FirstName = "Joy",
                            LastName = "Abshire",
                            UpdatedAt = new DateTime(2023, 12, 18, 5, 55, 54, 176, DateTimeKind.Local).AddTicks(5617)
                        },
                        new
                        {
                            Id = new Guid("81954489-a3a5-4505-a0ae-d3abd6f2ff27"),
                            CreatedAt = new DateTime(2022, 1, 19, 15, 44, 24, 787, DateTimeKind.Local).AddTicks(7936),
                            FirstName = "Arturo",
                            LastName = "Kihn",
                            UpdatedAt = new DateTime(2023, 5, 5, 13, 29, 35, 973, DateTimeKind.Local).AddTicks(7737)
                        },
                        new
                        {
                            Id = new Guid("e034d221-0cff-49ec-a4b5-ed77a21966c4"),
                            CreatedAt = new DateTime(2022, 2, 12, 5, 40, 13, 914, DateTimeKind.Local).AddTicks(4365),
                            FirstName = "Faye",
                            LastName = "Bartell",
                            UpdatedAt = new DateTime(2023, 11, 24, 13, 32, 6, 916, DateTimeKind.Local).AddTicks(6769)
                        },
                        new
                        {
                            Id = new Guid("42992f0d-5e8c-409e-99b3-cbb24101dbae"),
                            CreatedAt = new DateTime(2022, 8, 26, 9, 41, 23, 928, DateTimeKind.Local).AddTicks(7145),
                            FirstName = "Maureen",
                            LastName = "Dare",
                            UpdatedAt = new DateTime(2023, 8, 4, 12, 59, 9, 998, DateTimeKind.Local).AddTicks(9911)
                        },
                        new
                        {
                            Id = new Guid("aad8f955-3fdd-4081-936d-585ff626af74"),
                            CreatedAt = new DateTime(2022, 10, 15, 8, 7, 8, 779, DateTimeKind.Local).AddTicks(8845),
                            FirstName = "Dana",
                            LastName = "Considine",
                            UpdatedAt = new DateTime(2023, 2, 27, 12, 24, 59, 322, DateTimeKind.Local).AddTicks(3321)
                        },
                        new
                        {
                            Id = new Guid("5c7fd8ad-b892-4566-8272-e890c888cc82"),
                            CreatedAt = new DateTime(2022, 12, 14, 1, 41, 19, 908, DateTimeKind.Local).AddTicks(7649),
                            FirstName = "Debra",
                            LastName = "Kilback",
                            UpdatedAt = new DateTime(2023, 12, 26, 18, 54, 56, 300, DateTimeKind.Local).AddTicks(1401)
                        },
                        new
                        {
                            Id = new Guid("403c0f2a-e53c-4c20-b7cb-4d6e78340a8f"),
                            CreatedAt = new DateTime(2023, 4, 28, 1, 49, 18, 990, DateTimeKind.Local).AddTicks(5727),
                            FirstName = "Ramon",
                            LastName = "Willms",
                            UpdatedAt = new DateTime(2023, 5, 24, 12, 2, 20, 203, DateTimeKind.Local).AddTicks(9850)
                        },
                        new
                        {
                            Id = new Guid("85cc2f60-e1c3-4209-b144-ba10977a59b6"),
                            CreatedAt = new DateTime(2023, 5, 18, 6, 15, 12, 697, DateTimeKind.Local).AddTicks(2499),
                            FirstName = "Ramon",
                            LastName = "Orn",
                            UpdatedAt = new DateTime(2023, 9, 14, 7, 0, 6, 187, DateTimeKind.Local).AddTicks(6066)
                        },
                        new
                        {
                            Id = new Guid("4c50601b-a6ed-4c71-a05e-1beac931f158"),
                            CreatedAt = new DateTime(2022, 11, 19, 14, 30, 55, 20, DateTimeKind.Local).AddTicks(383),
                            FirstName = "Victor",
                            LastName = "Schinner",
                            UpdatedAt = new DateTime(2023, 11, 12, 23, 40, 35, 727, DateTimeKind.Local).AddTicks(8129)
                        },
                        new
                        {
                            Id = new Guid("1378357a-6a55-46a6-a9ed-4f91267be4ae"),
                            CreatedAt = new DateTime(2023, 10, 3, 19, 53, 30, 997, DateTimeKind.Local).AddTicks(2746),
                            FirstName = "Perry",
                            LastName = "Boehm",
                            UpdatedAt = new DateTime(2023, 12, 22, 14, 48, 13, 945, DateTimeKind.Local).AddTicks(5980)
                        },
                        new
                        {
                            Id = new Guid("ced3de6f-d320-4445-ac44-433627251ae8"),
                            CreatedAt = new DateTime(2023, 1, 15, 18, 0, 19, 542, DateTimeKind.Local).AddTicks(6960),
                            FirstName = "Samantha",
                            LastName = "Lakin",
                            UpdatedAt = new DateTime(2023, 11, 8, 9, 56, 12, 756, DateTimeKind.Local).AddTicks(9721)
                        },
                        new
                        {
                            Id = new Guid("924c9777-e4d7-4640-80f5-07d0d09872e2"),
                            CreatedAt = new DateTime(2023, 8, 7, 23, 16, 58, 989, DateTimeKind.Local).AddTicks(864),
                            FirstName = "Elena",
                            LastName = "Huels",
                            UpdatedAt = new DateTime(2023, 3, 30, 2, 26, 27, 585, DateTimeKind.Local).AddTicks(4384)
                        },
                        new
                        {
                            Id = new Guid("15366fcc-6f4e-4ff6-b955-32b61430f108"),
                            CreatedAt = new DateTime(2022, 3, 29, 21, 10, 43, 417, DateTimeKind.Local).AddTicks(5759),
                            FirstName = "Emmett",
                            LastName = "Reilly",
                            UpdatedAt = new DateTime(2023, 12, 14, 19, 24, 54, 846, DateTimeKind.Local).AddTicks(3548)
                        },
                        new
                        {
                            Id = new Guid("2977faeb-8f9f-4bde-bc4b-e87f6caafcc3"),
                            CreatedAt = new DateTime(2022, 3, 8, 18, 10, 3, 819, DateTimeKind.Local).AddTicks(4090),
                            FirstName = "Toby",
                            LastName = "Mitchell",
                            UpdatedAt = new DateTime(2023, 6, 11, 8, 23, 54, 87, DateTimeKind.Local).AddTicks(804)
                        },
                        new
                        {
                            Id = new Guid("2fbf9fd8-21f7-4bf0-a343-0960d345437a"),
                            CreatedAt = new DateTime(2023, 11, 14, 22, 53, 53, 213, DateTimeKind.Local).AddTicks(691),
                            FirstName = "Betsy",
                            LastName = "Pouros",
                            UpdatedAt = new DateTime(2023, 9, 21, 15, 2, 44, 591, DateTimeKind.Local).AddTicks(8246)
                        },
                        new
                        {
                            Id = new Guid("52bbe783-ac69-43b0-a894-d7d2afac5aea"),
                            CreatedAt = new DateTime(2022, 6, 27, 16, 25, 27, 462, DateTimeKind.Local).AddTicks(6218),
                            FirstName = "Tommie",
                            LastName = "Harber",
                            UpdatedAt = new DateTime(2023, 4, 25, 6, 47, 38, 859, DateTimeKind.Local).AddTicks(4102)
                        },
                        new
                        {
                            Id = new Guid("39cdbaf3-c304-4939-9377-aa6362eb8e77"),
                            CreatedAt = new DateTime(2023, 3, 17, 20, 56, 48, 767, DateTimeKind.Local).AddTicks(4920),
                            FirstName = "Ron",
                            LastName = "Reilly",
                            UpdatedAt = new DateTime(2023, 6, 27, 7, 1, 33, 631, DateTimeKind.Local).AddTicks(8249)
                        },
                        new
                        {
                            Id = new Guid("881e960c-f548-470c-90ef-9df8755c84a6"),
                            CreatedAt = new DateTime(2023, 7, 24, 14, 57, 43, 399, DateTimeKind.Local).AddTicks(860),
                            FirstName = "Ronald",
                            LastName = "Hane",
                            UpdatedAt = new DateTime(2023, 5, 9, 4, 33, 48, 72, DateTimeKind.Local).AddTicks(4063)
                        },
                        new
                        {
                            Id = new Guid("de44bc35-47c9-4235-9df8-e2f14ea45a6b"),
                            CreatedAt = new DateTime(2023, 4, 1, 14, 53, 36, 72, DateTimeKind.Local).AddTicks(7381),
                            FirstName = "Anita",
                            LastName = "Harris",
                            UpdatedAt = new DateTime(2023, 6, 23, 19, 56, 30, 847, DateTimeKind.Local).AddTicks(7355)
                        },
                        new
                        {
                            Id = new Guid("128ddc44-084a-46b4-ae28-fa4d33c80aa9"),
                            CreatedAt = new DateTime(2023, 8, 27, 18, 25, 57, 417, DateTimeKind.Local).AddTicks(4536),
                            FirstName = "Cassandra",
                            LastName = "Purdy",
                            UpdatedAt = new DateTime(2023, 9, 29, 21, 2, 18, 332, DateTimeKind.Local).AddTicks(5522)
                        },
                        new
                        {
                            Id = new Guid("738485eb-b2e3-4d2d-b4a2-7d0f3879be5b"),
                            CreatedAt = new DateTime(2022, 11, 30, 8, 28, 44, 966, DateTimeKind.Local).AddTicks(9634),
                            FirstName = "Lela",
                            LastName = "Crona",
                            UpdatedAt = new DateTime(2023, 7, 19, 20, 6, 41, 814, DateTimeKind.Local).AddTicks(731)
                        },
                        new
                        {
                            Id = new Guid("259894de-3aeb-4d40-9103-1b6e55ccf3c8"),
                            CreatedAt = new DateTime(2022, 7, 11, 9, 8, 33, 28, DateTimeKind.Local).AddTicks(7181),
                            FirstName = "Kyle",
                            LastName = "Nienow",
                            UpdatedAt = new DateTime(2023, 12, 11, 18, 20, 15, 928, DateTimeKind.Local).AddTicks(163)
                        },
                        new
                        {
                            Id = new Guid("9bc0e55c-311f-4f76-9524-034a1b412894"),
                            CreatedAt = new DateTime(2022, 12, 5, 0, 18, 14, 986, DateTimeKind.Local).AddTicks(9798),
                            FirstName = "Joyce",
                            LastName = "Block",
                            UpdatedAt = new DateTime(2023, 6, 14, 21, 29, 2, 833, DateTimeKind.Local).AddTicks(9992)
                        },
                        new
                        {
                            Id = new Guid("cecd9800-016f-4a72-829a-8f296cf60c4d"),
                            CreatedAt = new DateTime(2022, 6, 13, 9, 18, 39, 149, DateTimeKind.Local).AddTicks(3257),
                            FirstName = "John",
                            LastName = "Hand",
                            UpdatedAt = new DateTime(2023, 4, 15, 16, 42, 8, 189, DateTimeKind.Local).AddTicks(2183)
                        },
                        new
                        {
                            Id = new Guid("de5111fd-b982-42ec-acb0-b05b8e00af28"),
                            CreatedAt = new DateTime(2023, 3, 23, 6, 4, 53, 131, DateTimeKind.Local).AddTicks(3667),
                            FirstName = "Elsa",
                            LastName = "Tremblay",
                            UpdatedAt = new DateTime(2023, 12, 20, 18, 24, 23, 798, DateTimeKind.Local).AddTicks(7177)
                        },
                        new
                        {
                            Id = new Guid("127165c8-deed-439c-8d65-028dca913894"),
                            CreatedAt = new DateTime(2022, 9, 30, 9, 13, 9, 753, DateTimeKind.Local).AddTicks(1935),
                            FirstName = "Sheryl",
                            LastName = "Konopelski",
                            UpdatedAt = new DateTime(2023, 5, 7, 19, 29, 34, 959, DateTimeKind.Local).AddTicks(6826)
                        },
                        new
                        {
                            Id = new Guid("8cf44d0a-8588-4332-b73c-2130105c7091"),
                            CreatedAt = new DateTime(2023, 3, 28, 17, 1, 16, 472, DateTimeKind.Local).AddTicks(172),
                            FirstName = "Alma",
                            LastName = "Blanda",
                            UpdatedAt = new DateTime(2023, 1, 29, 6, 10, 43, 197, DateTimeKind.Local).AddTicks(5046)
                        },
                        new
                        {
                            Id = new Guid("490b76d4-9cb1-4583-b7f8-8c4568a42dce"),
                            CreatedAt = new DateTime(2022, 9, 2, 1, 7, 15, 804, DateTimeKind.Local).AddTicks(9962),
                            FirstName = "Kerry",
                            LastName = "Vandervort",
                            UpdatedAt = new DateTime(2023, 6, 26, 17, 40, 53, 850, DateTimeKind.Local).AddTicks(489)
                        },
                        new
                        {
                            Id = new Guid("d46a1f17-4eaa-4a61-a49d-e653c134e4f9"),
                            CreatedAt = new DateTime(2023, 1, 12, 20, 4, 2, 640, DateTimeKind.Local).AddTicks(975),
                            FirstName = "Robin",
                            LastName = "Leannon",
                            UpdatedAt = new DateTime(2023, 3, 2, 14, 24, 10, 931, DateTimeKind.Local).AddTicks(6184)
                        },
                        new
                        {
                            Id = new Guid("79d37e38-7d7c-4c52-9845-1a1c5b304b90"),
                            CreatedAt = new DateTime(2022, 5, 23, 21, 56, 40, 352, DateTimeKind.Local).AddTicks(5112),
                            FirstName = "Charles",
                            LastName = "Volkman",
                            UpdatedAt = new DateTime(2024, 1, 11, 12, 50, 35, 30, DateTimeKind.Local).AddTicks(2882)
                        },
                        new
                        {
                            Id = new Guid("b7f3e52f-2c18-4fd7-89d4-5a080fb84f56"),
                            CreatedAt = new DateTime(2022, 11, 24, 0, 7, 33, 229, DateTimeKind.Local).AddTicks(7256),
                            FirstName = "Russell",
                            LastName = "Ruecker",
                            UpdatedAt = new DateTime(2023, 10, 23, 9, 46, 57, 381, DateTimeKind.Local).AddTicks(8081)
                        },
                        new
                        {
                            Id = new Guid("5100d5a4-dcbc-4591-989a-86dba2529385"),
                            CreatedAt = new DateTime(2023, 6, 26, 3, 59, 51, 25, DateTimeKind.Local).AddTicks(4078),
                            FirstName = "Tommie",
                            LastName = "Hayes",
                            UpdatedAt = new DateTime(2023, 3, 21, 11, 57, 52, 94, DateTimeKind.Local).AddTicks(4902)
                        },
                        new
                        {
                            Id = new Guid("5b5cf7f7-d883-4f3f-b29d-e3e8a6fbd9d2"),
                            CreatedAt = new DateTime(2022, 2, 9, 8, 10, 8, 170, DateTimeKind.Local).AddTicks(1342),
                            FirstName = "Belinda",
                            LastName = "Larkin",
                            UpdatedAt = new DateTime(2023, 3, 29, 2, 40, 48, 470, DateTimeKind.Local).AddTicks(620)
                        },
                        new
                        {
                            Id = new Guid("b737f84b-1c62-42f6-a07e-69630400856d"),
                            CreatedAt = new DateTime(2022, 5, 29, 2, 59, 59, 311, DateTimeKind.Local).AddTicks(9758),
                            FirstName = "Adam",
                            LastName = "Conroy",
                            UpdatedAt = new DateTime(2023, 1, 22, 21, 44, 25, 877, DateTimeKind.Local).AddTicks(686)
                        },
                        new
                        {
                            Id = new Guid("9f12a031-cf12-4d1b-bb75-36dfc18fcdb2"),
                            CreatedAt = new DateTime(2023, 1, 1, 23, 28, 2, 510, DateTimeKind.Local).AddTicks(8442),
                            FirstName = "Jimmie",
                            LastName = "Wisoky",
                            UpdatedAt = new DateTime(2023, 4, 4, 8, 2, 21, 549, DateTimeKind.Local).AddTicks(3293)
                        },
                        new
                        {
                            Id = new Guid("8dc84347-a3eb-45c7-b74a-d6ef76bbd09a"),
                            CreatedAt = new DateTime(2023, 10, 2, 0, 3, 49, 784, DateTimeKind.Local).AddTicks(5299),
                            FirstName = "Simon",
                            LastName = "Gaylord",
                            UpdatedAt = new DateTime(2023, 8, 7, 3, 2, 3, 647, DateTimeKind.Local).AddTicks(4532)
                        },
                        new
                        {
                            Id = new Guid("e56d3574-e1e9-4761-9709-bfcbb81a02d9"),
                            CreatedAt = new DateTime(2023, 5, 12, 12, 20, 3, 875, DateTimeKind.Local).AddTicks(1896),
                            FirstName = "Dominic",
                            LastName = "Reynolds",
                            UpdatedAt = new DateTime(2023, 10, 5, 18, 27, 20, 34, DateTimeKind.Local).AddTicks(5986)
                        },
                        new
                        {
                            Id = new Guid("9235af73-a21f-4747-a21b-fcb3ef540c3d"),
                            CreatedAt = new DateTime(2022, 2, 11, 2, 38, 45, 160, DateTimeKind.Local).AddTicks(5283),
                            FirstName = "Emma",
                            LastName = "Sanford",
                            UpdatedAt = new DateTime(2023, 9, 13, 16, 18, 59, 57, DateTimeKind.Local).AddTicks(6905)
                        },
                        new
                        {
                            Id = new Guid("4ff50481-a1ad-431b-9c1b-d89c94150808"),
                            CreatedAt = new DateTime(2022, 12, 7, 5, 33, 22, 405, DateTimeKind.Local).AddTicks(2918),
                            FirstName = "Wade",
                            LastName = "Roberts",
                            UpdatedAt = new DateTime(2023, 8, 29, 4, 18, 40, 545, DateTimeKind.Local).AddTicks(2973)
                        },
                        new
                        {
                            Id = new Guid("3e32c3a6-e323-4e22-b15d-f7825787dda8"),
                            CreatedAt = new DateTime(2023, 4, 8, 18, 0, 41, 930, DateTimeKind.Local).AddTicks(9841),
                            FirstName = "Joe",
                            LastName = "Heidenreich",
                            UpdatedAt = new DateTime(2023, 11, 23, 18, 43, 45, 974, DateTimeKind.Local).AddTicks(7813)
                        },
                        new
                        {
                            Id = new Guid("b5b1f68f-b9a8-4540-9946-33258b8019b1"),
                            CreatedAt = new DateTime(2023, 6, 17, 6, 15, 5, 93, DateTimeKind.Local).AddTicks(4937),
                            FirstName = "Angelica",
                            LastName = "Kiehn",
                            UpdatedAt = new DateTime(2023, 5, 11, 10, 8, 45, 19, DateTimeKind.Local).AddTicks(4443)
                        },
                        new
                        {
                            Id = new Guid("b883b21f-a070-438f-b123-d671defd00c5"),
                            CreatedAt = new DateTime(2022, 10, 3, 18, 0, 40, 690, DateTimeKind.Local).AddTicks(9171),
                            FirstName = "Doug",
                            LastName = "Farrell",
                            UpdatedAt = new DateTime(2023, 10, 25, 10, 33, 20, 769, DateTimeKind.Local).AddTicks(6079)
                        },
                        new
                        {
                            Id = new Guid("56fec888-09eb-4307-b01b-6e13282b91a4"),
                            CreatedAt = new DateTime(2022, 6, 27, 0, 42, 38, 562, DateTimeKind.Local).AddTicks(5924),
                            FirstName = "Austin",
                            LastName = "Sanford",
                            UpdatedAt = new DateTime(2023, 12, 14, 22, 26, 2, 58, DateTimeKind.Local).AddTicks(3301)
                        },
                        new
                        {
                            Id = new Guid("57135006-f657-4521-9bb7-e6db49bac56f"),
                            CreatedAt = new DateTime(2022, 11, 12, 21, 33, 12, 426, DateTimeKind.Local).AddTicks(5705),
                            FirstName = "Courtney",
                            LastName = "Hartmann",
                            UpdatedAt = new DateTime(2023, 11, 13, 21, 58, 45, 69, DateTimeKind.Local).AddTicks(1270)
                        },
                        new
                        {
                            Id = new Guid("701eb445-f304-45e3-9cf7-7a0f093b62e8"),
                            CreatedAt = new DateTime(2023, 1, 28, 3, 37, 45, 142, DateTimeKind.Local).AddTicks(5044),
                            FirstName = "Tommy",
                            LastName = "Fay",
                            UpdatedAt = new DateTime(2023, 12, 27, 13, 4, 42, 751, DateTimeKind.Local).AddTicks(6931)
                        },
                        new
                        {
                            Id = new Guid("f74e5a58-a478-4a73-b379-54b0f6df39d2"),
                            CreatedAt = new DateTime(2023, 7, 29, 20, 26, 54, 569, DateTimeKind.Local).AddTicks(9),
                            FirstName = "Wilma",
                            LastName = "Williamson",
                            UpdatedAt = new DateTime(2024, 1, 3, 14, 31, 51, 853, DateTimeKind.Local).AddTicks(7391)
                        },
                        new
                        {
                            Id = new Guid("81233293-23ba-49ea-b4d5-501103ad8569"),
                            CreatedAt = new DateTime(2023, 10, 15, 17, 22, 46, 483, DateTimeKind.Local).AddTicks(7588),
                            FirstName = "Salvador",
                            LastName = "Marquardt",
                            UpdatedAt = new DateTime(2023, 10, 23, 22, 13, 41, 593, DateTimeKind.Local).AddTicks(7576)
                        },
                        new
                        {
                            Id = new Guid("25ffa478-a453-409b-83ba-5aae2b9144fe"),
                            CreatedAt = new DateTime(2023, 12, 11, 7, 58, 32, 872, DateTimeKind.Local).AddTicks(8973),
                            FirstName = "Suzanne",
                            LastName = "O'Reilly",
                            UpdatedAt = new DateTime(2023, 12, 31, 5, 19, 43, 632, DateTimeKind.Local).AddTicks(7771)
                        },
                        new
                        {
                            Id = new Guid("5293a086-5202-448c-a17b-f965c33b5635"),
                            CreatedAt = new DateTime(2022, 4, 15, 16, 28, 28, 87, DateTimeKind.Local).AddTicks(5526),
                            FirstName = "Gladys",
                            LastName = "Koelpin",
                            UpdatedAt = new DateTime(2023, 9, 8, 5, 34, 59, 894, DateTimeKind.Local).AddTicks(3785)
                        },
                        new
                        {
                            Id = new Guid("bb64bf64-d3e4-4702-8778-176e1abff73f"),
                            CreatedAt = new DateTime(2022, 11, 14, 10, 31, 43, 674, DateTimeKind.Local).AddTicks(2096),
                            FirstName = "Garry",
                            LastName = "Hills",
                            UpdatedAt = new DateTime(2023, 3, 15, 15, 2, 15, 591, DateTimeKind.Local).AddTicks(1714)
                        },
                        new
                        {
                            Id = new Guid("294c18f8-686f-4cf0-8a11-b8b035df3650"),
                            CreatedAt = new DateTime(2022, 12, 13, 14, 51, 53, 738, DateTimeKind.Local).AddTicks(7621),
                            FirstName = "Vera",
                            LastName = "Kulas",
                            UpdatedAt = new DateTime(2023, 6, 4, 16, 42, 0, 533, DateTimeKind.Local).AddTicks(4715)
                        },
                        new
                        {
                            Id = new Guid("e82211e6-fc2a-4c23-8ab9-b7a315517586"),
                            CreatedAt = new DateTime(2022, 2, 3, 22, 58, 12, 32, DateTimeKind.Local).AddTicks(8464),
                            FirstName = "Emily",
                            LastName = "Gaylord",
                            UpdatedAt = new DateTime(2023, 7, 6, 7, 59, 23, 696, DateTimeKind.Local).AddTicks(9181)
                        },
                        new
                        {
                            Id = new Guid("6c9fbb9f-3d28-4e37-b711-afda80129876"),
                            CreatedAt = new DateTime(2022, 12, 31, 4, 53, 41, 56, DateTimeKind.Local).AddTicks(1596),
                            FirstName = "Benjamin",
                            LastName = "Doyle",
                            UpdatedAt = new DateTime(2023, 1, 16, 17, 20, 8, 630, DateTimeKind.Local).AddTicks(2876)
                        },
                        new
                        {
                            Id = new Guid("c3b6c1a4-bf42-4fc0-8640-19cd6ac6988b"),
                            CreatedAt = new DateTime(2022, 2, 15, 1, 6, 14, 750, DateTimeKind.Local).AddTicks(7081),
                            FirstName = "Claude",
                            LastName = "Greenholt",
                            UpdatedAt = new DateTime(2023, 5, 5, 3, 47, 50, 783, DateTimeKind.Local).AddTicks(6957)
                        },
                        new
                        {
                            Id = new Guid("dc0d690f-573c-410e-a790-573ea0d48ff5"),
                            CreatedAt = new DateTime(2022, 4, 27, 15, 22, 11, 146, DateTimeKind.Local).AddTicks(9036),
                            FirstName = "Ben",
                            LastName = "Ankunding",
                            UpdatedAt = new DateTime(2023, 1, 19, 2, 37, 52, 389, DateTimeKind.Local).AddTicks(7062)
                        },
                        new
                        {
                            Id = new Guid("8e5f0496-ef5c-4314-be29-a370b8477453"),
                            CreatedAt = new DateTime(2022, 4, 16, 15, 58, 38, 933, DateTimeKind.Local).AddTicks(121),
                            FirstName = "Carlton",
                            LastName = "Brekke",
                            UpdatedAt = new DateTime(2023, 9, 16, 16, 59, 49, 262, DateTimeKind.Local).AddTicks(7047)
                        },
                        new
                        {
                            Id = new Guid("9fbafa0e-c90f-4be7-8950-7182f8c9cb9b"),
                            CreatedAt = new DateTime(2023, 7, 17, 18, 19, 48, 241, DateTimeKind.Local).AddTicks(6729),
                            FirstName = "Margaret",
                            LastName = "Nader",
                            UpdatedAt = new DateTime(2023, 5, 1, 7, 34, 32, 819, DateTimeKind.Local).AddTicks(9515)
                        },
                        new
                        {
                            Id = new Guid("beb08c55-300c-49f6-957f-f17f67130332"),
                            CreatedAt = new DateTime(2022, 6, 21, 9, 1, 18, 871, DateTimeKind.Local).AddTicks(2607),
                            FirstName = "Carroll",
                            LastName = "Reilly",
                            UpdatedAt = new DateTime(2023, 8, 12, 4, 25, 35, 287, DateTimeKind.Local).AddTicks(6433)
                        },
                        new
                        {
                            Id = new Guid("02f142aa-2d39-40f5-9362-8d74475df3f9"),
                            CreatedAt = new DateTime(2023, 7, 26, 6, 40, 22, 733, DateTimeKind.Local).AddTicks(1197),
                            FirstName = "Bryan",
                            LastName = "Schimmel",
                            UpdatedAt = new DateTime(2023, 7, 16, 5, 35, 58, 701, DateTimeKind.Local).AddTicks(218)
                        },
                        new
                        {
                            Id = new Guid("bcefbd0f-0788-4d5b-8506-43810028f2c5"),
                            CreatedAt = new DateTime(2023, 9, 9, 23, 49, 25, 878, DateTimeKind.Local).AddTicks(2358),
                            FirstName = "Sherry",
                            LastName = "Parisian",
                            UpdatedAt = new DateTime(2023, 9, 30, 8, 7, 43, 772, DateTimeKind.Local).AddTicks(1569)
                        },
                        new
                        {
                            Id = new Guid("a985b94c-023a-499c-934c-7448ff952337"),
                            CreatedAt = new DateTime(2022, 2, 26, 1, 30, 20, 527, DateTimeKind.Local).AddTicks(419),
                            FirstName = "Sara",
                            LastName = "Bartoletti",
                            UpdatedAt = new DateTime(2023, 8, 9, 17, 26, 31, 202, DateTimeKind.Local).AddTicks(2217)
                        },
                        new
                        {
                            Id = new Guid("8aa8f234-1934-416a-bee9-f661329b15dd"),
                            CreatedAt = new DateTime(2022, 10, 22, 1, 56, 6, 47, DateTimeKind.Local).AddTicks(6445),
                            FirstName = "Marcella",
                            LastName = "Schmeler",
                            UpdatedAt = new DateTime(2023, 7, 16, 23, 47, 19, 87, DateTimeKind.Local).AddTicks(1173)
                        },
                        new
                        {
                            Id = new Guid("70c31c70-0c02-438a-a8f8-054524bce917"),
                            CreatedAt = new DateTime(2023, 5, 29, 1, 6, 17, 900, DateTimeKind.Local).AddTicks(4964),
                            FirstName = "Lee",
                            LastName = "Dickens",
                            UpdatedAt = new DateTime(2023, 4, 4, 16, 38, 34, 477, DateTimeKind.Local).AddTicks(110)
                        },
                        new
                        {
                            Id = new Guid("690d3829-303f-49df-a9bc-693ba9b4f99c"),
                            CreatedAt = new DateTime(2022, 3, 27, 10, 28, 47, 427, DateTimeKind.Local).AddTicks(5310),
                            FirstName = "Jana",
                            LastName = "Kautzer",
                            UpdatedAt = new DateTime(2023, 7, 19, 3, 2, 31, 612, DateTimeKind.Local).AddTicks(5017)
                        },
                        new
                        {
                            Id = new Guid("2237b39a-b809-42d3-8c0e-410f651ea28c"),
                            CreatedAt = new DateTime(2022, 10, 14, 7, 22, 55, 391, DateTimeKind.Local).AddTicks(1360),
                            FirstName = "Trevor",
                            LastName = "Kuhn",
                            UpdatedAt = new DateTime(2023, 4, 14, 10, 22, 12, 49, DateTimeKind.Local).AddTicks(5476)
                        },
                        new
                        {
                            Id = new Guid("548fa41b-e9ca-4ca0-ab50-8432d6916c04"),
                            CreatedAt = new DateTime(2022, 12, 4, 3, 7, 27, 665, DateTimeKind.Local).AddTicks(8735),
                            FirstName = "Melinda",
                            LastName = "Gutkowski",
                            UpdatedAt = new DateTime(2023, 12, 24, 0, 43, 58, 772, DateTimeKind.Local).AddTicks(8850)
                        },
                        new
                        {
                            Id = new Guid("fe3107c8-4b65-4ccf-aff1-60e1cedbe2cf"),
                            CreatedAt = new DateTime(2023, 12, 20, 13, 3, 3, 408, DateTimeKind.Local).AddTicks(5695),
                            FirstName = "Conrad",
                            LastName = "Kuphal",
                            UpdatedAt = new DateTime(2023, 7, 8, 3, 40, 30, 997, DateTimeKind.Local).AddTicks(7012)
                        },
                        new
                        {
                            Id = new Guid("96a2b6f3-c510-48fa-b19d-24db1b30893a"),
                            CreatedAt = new DateTime(2022, 5, 9, 16, 56, 36, 278, DateTimeKind.Local).AddTicks(1085),
                            FirstName = "Rochelle",
                            LastName = "McClure",
                            UpdatedAt = new DateTime(2023, 7, 28, 12, 48, 49, 284, DateTimeKind.Local).AddTicks(4537)
                        },
                        new
                        {
                            Id = new Guid("9729352a-c101-460f-bab5-64be7c2996c7"),
                            CreatedAt = new DateTime(2022, 10, 1, 13, 51, 53, 95, DateTimeKind.Local).AddTicks(1719),
                            FirstName = "Craig",
                            LastName = "Bogan",
                            UpdatedAt = new DateTime(2023, 5, 23, 1, 28, 39, 913, DateTimeKind.Local).AddTicks(9839)
                        },
                        new
                        {
                            Id = new Guid("27349a80-9aa1-4d45-8296-8d3c2a2a5aa5"),
                            CreatedAt = new DateTime(2023, 4, 14, 17, 49, 27, 716, DateTimeKind.Local).AddTicks(4352),
                            FirstName = "Mabel",
                            LastName = "Wiza",
                            UpdatedAt = new DateTime(2023, 5, 7, 16, 26, 19, 651, DateTimeKind.Local).AddTicks(4696)
                        },
                        new
                        {
                            Id = new Guid("dd3f126d-1fae-4b6f-a04f-7a209f7e0ccc"),
                            CreatedAt = new DateTime(2022, 12, 23, 7, 26, 23, 203, DateTimeKind.Local).AddTicks(9178),
                            FirstName = "Maryann",
                            LastName = "Nicolas",
                            UpdatedAt = new DateTime(2023, 4, 7, 12, 48, 15, 425, DateTimeKind.Local).AddTicks(3522)
                        },
                        new
                        {
                            Id = new Guid("afc43d51-252b-49b3-9e5c-fb536e0322c3"),
                            CreatedAt = new DateTime(2023, 9, 11, 16, 37, 54, 301, DateTimeKind.Local).AddTicks(7791),
                            FirstName = "Josh",
                            LastName = "Bode",
                            UpdatedAt = new DateTime(2023, 12, 21, 1, 35, 12, 231, DateTimeKind.Local).AddTicks(4388)
                        },
                        new
                        {
                            Id = new Guid("731b892d-5ac6-4e7c-8817-1842a44ba0a7"),
                            CreatedAt = new DateTime(2023, 9, 8, 5, 35, 58, 749, DateTimeKind.Local).AddTicks(3408),
                            FirstName = "Sheila",
                            LastName = "Kutch",
                            UpdatedAt = new DateTime(2023, 11, 26, 11, 4, 19, 656, DateTimeKind.Local).AddTicks(1665)
                        },
                        new
                        {
                            Id = new Guid("c2ff0164-d3f3-4705-9644-cf8286f24ab0"),
                            CreatedAt = new DateTime(2023, 12, 15, 1, 14, 6, 687, DateTimeKind.Local).AddTicks(9791),
                            FirstName = "Bob",
                            LastName = "Price",
                            UpdatedAt = new DateTime(2023, 6, 3, 1, 33, 29, 199, DateTimeKind.Local).AddTicks(286)
                        },
                        new
                        {
                            Id = new Guid("76f1e3bc-b6fa-4f97-9d15-ebe29c683917"),
                            CreatedAt = new DateTime(2023, 8, 2, 21, 15, 42, 460, DateTimeKind.Local).AddTicks(4637),
                            FirstName = "Terrell",
                            LastName = "Beatty",
                            UpdatedAt = new DateTime(2023, 2, 2, 9, 59, 22, 906, DateTimeKind.Local).AddTicks(4826)
                        },
                        new
                        {
                            Id = new Guid("ee5df22e-b9e0-43eb-86d3-c8891397922f"),
                            CreatedAt = new DateTime(2023, 11, 6, 1, 53, 53, 297, DateTimeKind.Local).AddTicks(1871),
                            FirstName = "Gwendolyn",
                            LastName = "Beer",
                            UpdatedAt = new DateTime(2023, 7, 12, 17, 1, 18, 360, DateTimeKind.Local).AddTicks(5332)
                        },
                        new
                        {
                            Id = new Guid("5e55f9cb-2cf6-48f5-9931-13cf23dd38d7"),
                            CreatedAt = new DateTime(2022, 10, 7, 17, 32, 28, 946, DateTimeKind.Local).AddTicks(2162),
                            FirstName = "Josephine",
                            LastName = "Hodkiewicz",
                            UpdatedAt = new DateTime(2023, 12, 15, 17, 41, 49, 97, DateTimeKind.Local).AddTicks(9385)
                        },
                        new
                        {
                            Id = new Guid("8a363355-0295-4e1c-ae7f-982d627ac026"),
                            CreatedAt = new DateTime(2022, 7, 5, 11, 58, 24, 81, DateTimeKind.Local).AddTicks(9600),
                            FirstName = "Donna",
                            LastName = "Zboncak",
                            UpdatedAt = new DateTime(2023, 5, 13, 17, 55, 9, 969, DateTimeKind.Local).AddTicks(1563)
                        },
                        new
                        {
                            Id = new Guid("2e2b3a30-b75c-40c5-bd7f-aa5c3a9a9b8c"),
                            CreatedAt = new DateTime(2023, 1, 28, 1, 44, 0, 681, DateTimeKind.Local).AddTicks(1387),
                            FirstName = "Darryl",
                            LastName = "Rohan",
                            UpdatedAt = new DateTime(2024, 1, 4, 17, 54, 43, 388, DateTimeKind.Local).AddTicks(3565)
                        },
                        new
                        {
                            Id = new Guid("2007d817-6d73-4459-9672-a2e9697f153a"),
                            CreatedAt = new DateTime(2023, 4, 9, 3, 6, 58, 855, DateTimeKind.Local).AddTicks(2626),
                            FirstName = "Lynette",
                            LastName = "Reinger",
                            UpdatedAt = new DateTime(2023, 8, 28, 16, 12, 44, 672, DateTimeKind.Local).AddTicks(7690)
                        },
                        new
                        {
                            Id = new Guid("2a40f0d2-e1cd-47e4-995b-55bf95fb7dd0"),
                            CreatedAt = new DateTime(2023, 3, 18, 18, 34, 37, 942, DateTimeKind.Local).AddTicks(1562),
                            FirstName = "Ken",
                            LastName = "Kris",
                            UpdatedAt = new DateTime(2023, 6, 23, 1, 38, 20, 287, DateTimeKind.Local).AddTicks(159)
                        },
                        new
                        {
                            Id = new Guid("0063d2b4-3c9f-4a95-93e6-fe73d13ea76d"),
                            CreatedAt = new DateTime(2022, 12, 22, 14, 27, 22, 360, DateTimeKind.Local).AddTicks(3252),
                            FirstName = "Homer",
                            LastName = "Veum",
                            UpdatedAt = new DateTime(2023, 7, 17, 0, 11, 26, 395, DateTimeKind.Local).AddTicks(4056)
                        },
                        new
                        {
                            Id = new Guid("f792d5ce-c61d-4f06-bd43-72586bd8e928"),
                            CreatedAt = new DateTime(2023, 2, 10, 5, 15, 53, 517, DateTimeKind.Local).AddTicks(6941),
                            FirstName = "Ken",
                            LastName = "Hodkiewicz",
                            UpdatedAt = new DateTime(2023, 8, 9, 19, 15, 23, 58, DateTimeKind.Local).AddTicks(8788)
                        },
                        new
                        {
                            Id = new Guid("ba051e7a-72a8-477a-8539-0850bf247d83"),
                            CreatedAt = new DateTime(2023, 8, 28, 23, 33, 27, 120, DateTimeKind.Local).AddTicks(1097),
                            FirstName = "Juanita",
                            LastName = "Bosco",
                            UpdatedAt = new DateTime(2023, 7, 15, 14, 22, 43, 660, DateTimeKind.Local).AddTicks(7765)
                        },
                        new
                        {
                            Id = new Guid("4299ed41-ad1f-4789-a9a2-130a0f947c1d"),
                            CreatedAt = new DateTime(2022, 10, 25, 11, 45, 47, 190, DateTimeKind.Local).AddTicks(8021),
                            FirstName = "Stacy",
                            LastName = "Altenwerth",
                            UpdatedAt = new DateTime(2023, 1, 28, 1, 29, 30, 220, DateTimeKind.Local).AddTicks(3883)
                        },
                        new
                        {
                            Id = new Guid("6fd6a6a8-8011-4ce5-a62d-831a211e57f7"),
                            CreatedAt = new DateTime(2023, 8, 15, 1, 7, 58, 126, DateTimeKind.Local).AddTicks(7212),
                            FirstName = "Charlotte",
                            LastName = "Walsh",
                            UpdatedAt = new DateTime(2023, 4, 30, 11, 13, 25, 667, DateTimeKind.Local).AddTicks(9672)
                        },
                        new
                        {
                            Id = new Guid("4eaef2d8-c30d-4243-98c2-f216fcbfedf5"),
                            CreatedAt = new DateTime(2023, 7, 20, 0, 5, 12, 471, DateTimeKind.Local).AddTicks(1358),
                            FirstName = "Emily",
                            LastName = "Beatty",
                            UpdatedAt = new DateTime(2023, 11, 18, 3, 31, 2, 669, DateTimeKind.Local).AddTicks(4380)
                        },
                        new
                        {
                            Id = new Guid("6dbcb4e9-7a77-4ef8-8788-61041be204a6"),
                            CreatedAt = new DateTime(2023, 4, 12, 23, 19, 32, 321, DateTimeKind.Local).AddTicks(1460),
                            FirstName = "Bryan",
                            LastName = "Reichel",
                            UpdatedAt = new DateTime(2023, 4, 27, 13, 48, 43, 82, DateTimeKind.Local).AddTicks(7866)
                        });
                });

            modelBuilder.Entity("WikY.Entities.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("WikY.Entities.Articles.Article", b =>
                {
                    b.HasOne("WikY.Entities.Authors.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("WikY.Entities.Comments.Comment", b =>
                {
                    b.HasOne("WikY.Entities.Articles.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("WikY.Entities.Articles.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("WikY.Entities.Authors.Author", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
